## reference: http://docs.travis-ci.com/user/languages/r/

language: r
r:
  - bioc-devel

cache: packages
bioc_required: true

os:
  - linux
  - osx


apt_packages:
  - libfftw3-dev

r_packages:
  - covr
  - ape
  - ggplot2
  - tidyr

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"


after_failure:
  - ./travis-tool.sh dump_logs

## r_github_packages:
##   - jimhester/covr

after_success:
- Rscript -e 'library(covr); codecov()'

## notifications:
##   email:
##     on_success: change
##     on_failure: change

