environment:
  R_CHECK_ARGS: --no-manual

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

  
install:
  ps: Bootstrap

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc BiocStyle Biostrings EBImage
##  - travis-tool.sh install_bioc_deps
  
test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

